### ISSUE TITLE
Need to keep maintenance screen from showing until button clicked, any ideas team?

### ISSUE THREAD

**Issue by JM-Code1** [JM-Code1/com.kejejo.javastars#5]
Not a deal breaker, but it bugs me that I have to click to close the window each time I open the program.

**Comment by KevinM-Code** [comment]
The maintenance window opening at the same time is the same functionality as the model program. I believe this gives the user the option to edit searched files before actually searching them. I like it, but I am flexible. We still need (Number of files indexed: 0) on the maintenance Window and (Number of files indexed: 0) on the Main Search Window. Can you add them? See Model Application.

**Comment by JM-Code1** [comment]
Both Screens are updated to reflect the number of files indexed.
